global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "hr-service-node"
    metrics_path: "/api/metrics"
    file_sd_configs:
      - refresh_interval: 15s
        files:
          - "/etc/prometheus/jobs/hr-service-targets.json"

  - job_name: "nodeexporter"
    file_sd_configs:
      - files:
          - "/etc/prometheus/jobs/nodeexporter.yml"
        refresh_interval: 15s

  - job_name: "cadvisor"
    file_sd_configs:
      - files:
          - "/etc/prometheus/jobs/cadvisor.yml"
        refresh_interval: 15s

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx_exporter:9113"]
