stages:
  - deploy

deploy:
  stage: deploy
  script:
    - |
      cd $DEVOPS_DOCKER_WORKSPACE
      git fetch
      git checkout $CI_COMMIT_TAG
      docker-compose up -d --force-recreate --build
  when: manual
  only:
    refs:
      - /^v\d+\.\d+\.\d+$/
  tags:
    - alicloud
