version: '3.9'

networks:
  main-net:
    name: docker_default
    driver: bridge
  # monitor-net:
  #   name: monitor_monitor-net
  #   external: true

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /data/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'TZ=Asia/Shanghai'
    ports:
      - '3306:3306'
  # redis:
  #   image: redis:5.0.14
  #   restart: always
  #   volumes:
  #     - /data/redis:/data
  #   ports:
  #     - '6379:6379'
  nginx:
    image: 'nginx:1.23.0'
    restart: always
    container_name: nginx
    networks:
      - main-net
      # - monitor-net
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      # - ./nginx/html:/usr/share/nginx/html
      - ./nginx/html:/etc/nginx/html
      - ./nginx/key:/etc/nginx/key
      - ./nginx/logs:/var/log/nginx
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://nginx/server-status' ]
      interval: 1m30s
      timeout: 10s
      retries: 5
    ports:
      - '80:80'
      # - '443:443'
  frps:
    container_name: frps
    image: snowdreamtech/frps
    restart: always
    volumes:
        - './frp/frps.ini:/etc/frp/frps.ini'
    ports:
      - '6000:6000'
      - '7000-7010:7000-7010'
  ivelly-fe:
    image: qiujie8092916/ivelly-fe:latest
    restart: always
  hook:
    image: qiujie8092916/hook:latest
    restart: always