version: '3.9'

networks:
  main-net:
    name: docker_default
    driver: bridge
  monitor-net:
    name: monitor_monitor-net
    external: true

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /data/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'TZ=Asia/Shanghai'
    ports:
      - '3306:3306'
  # redis:
  #   image: redis:5.0.14
  #   restart: always
  #   volumes:
  #     - /data/redis:/data
  #   ports:
  #     - '6379:6379'
  nginx:
    image: 'nginx:1.23.0'
    restart: always
    networks:
      - main-net
      - monitor-net
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/key:/etc/nginx/key
      - /data/logs/nginx:/var/log/nginx
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://nginx/server-status' ]
      interval: 1m30s
      timeout: 10s
      retries: 5
    ports:
      - '80:80'
      # - '443:443'
  ivelly:
    image: ivelly:latest
    restart: always